#!/bin/bash
# pam-render
SCRIPT="screenplay.json"
OUTPUT="PAMPlayer"
QUALITY="l"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --script|-s)  SCRIPT="$2";  shift 2 ;;
        --output|-o)  OUTPUT="$2";  shift 2 ;;
        --quality|-q) QUALITY="$2"; shift 2 ;;
        *) SCRIPT="$1"; shift ;;
    esac
done

PAM_SCRIPT="$SCRIPT" manim -pq"$QUALITY" -o "${OUTPUT}.mp4" pam_player.py PAMPlayer